# Generated by Django 4.2.1 on 2023-05-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.IntegerField(max_length=10),
        ),
    ]
